# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  custom_rules_maven_java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run .ci/build.sh
        run: |
          cd custom-rules/maven-java
          .ci/build.sh

  custom_rules_maven_plsql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run .ci/build.sh
        run: |
          cd custom-rules/maven-plsql
          .ci/build.sh

  custom_rules_plain_java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v3
        with:
          path: custom-rules/plain-java/code
          key: ${{ runner.os }}-pmd-${{ hashFiles('custom-rules/plain-java/.ci/build.sh }}

      - name: Run .ci/build.sh
        run: |
          cd custom-rules/plain-java
          .ci/build.sh

  maven_simple_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run .ci/build.sh
        run: |
          cd maven/simple-project
          .ci/build.sh
